############################   IMPORTS  #############################

import sys
import random

tries = 0
length = 0


######################   ADDITIONAL FUNCTIONS  ######################

# # Helps the usert o evaluate if the random number is higher or lower than the introduced number.
# # If the user guees the number prints a congratulation and stops evaluating.
# # If the number is higher or lower, the rutine ask_user_number is called again and again incrementing the tries until the user guess the number.
def evaluate_number(user_number, random_number):
	global tries 
	tries += 1
	if random_number == user_number:
		print("Congratulations. You guessed the correct number in " + str(tries) + " tries.")
	else:
		if random_number > user_number:
			user_number = ask_user_number(False, 'higher')
		elif random_number < user_number:
			user_number = ask_user_number(False, 'lower')
		evaluate_number(user_number, random_number)


# # Gives the user hints about the number he intriduced. If it was higher or lower than the one generated by the program.
# # It also validates that the input from the user is a number and is positive.
def ask_user_number(first_time, higher_lower):
	global length
	while True:
		try:
			if first_time == True:
				user_number = int(input("Guess a " + str(length) + "-digit number: "))
			else:
				user_number = int(input("Try again. Guess a " + higher_lower + " number: "))
		except:
			print("Warning: Integer Value Expected")
			continue

		if len(str(user_number)) > int(length) or user_number < 0:
			print("Provide a positive number of length: {}".format(length))
			continue
		else:
			break

	return user_number

# # Generates the random number. The range is calculated re;ated to the number of digits it can have.
def gen_random():
	global length
	length = get_number_length()
	max_integer = int('9'*int(length))				# 9**length - To limit the range
	random_number = random.randint(0, max_integer)
	return random_number

# # Set the length of the random digits
def get_number_length():
	try:
		return sys.argv[1]			# # Get the firts argument
	except:
		return 1

# # Validates if the user wants to try again and if he answer yes or no.
def ask_user_try_again():
	while True:
		try_again = input("Do you want to try again? Yes/No:  \n")
		if try_again in ('Yes', 'yes'):
			return True
		elif try_again in ('No', 'no'):
			return False
		else:
			print("I did not understand what your answer is!!!")
			continue

	return user_number

# # Main rutine that calls all the other functions.
def mimsmind0_rutine():
	global tries
	tries = 0
	
	print("Let's play the mimsmind0 game.")
	random_number = gen_random()				# # Gets the random number that is related to the lenght specified byt eh user or the default length.
	print('RANDOM: ', random_number)
	user_number =ask_user_number(True, '')		# # Ask the user for the number he want to guess and validates if is valid.
	evaluate_number(user_number, random_number)		# # Evaluates the number given by the user and gives hints.
	return ask_user_try_again()						# # Ask user if he/she want to play again. Returns True or False.


##############################   MAIN  ##############################
def main():

	flag = True
	while flag == True:
		flag = mimsmind0_rutine()
		


if __name__ == '__main__':
	main()